### ISSUE TITLE
Clarify license for redistribution

### ISSUE THREAD

**Issue by jasperla** [ttmo-O/x86-manpages#2]
I'd like to package these helpful manpages for further redistribution as part of the OpenBSD ports tree. However I'd like ensure the license on the manpages is more clear than this to allow us to distribute packages:

```
Copyleft TTMO 2020 (Turkish Unofficial Chamber of Reverse Engineers - https://ttmo.re).
```

'Copyleft' per-se is not a license AFAICS, furthermore since these manpages are generated from the Intel SDM, does that allow redistribution of this derivative work?

**Comment by figbux** [comment]
@erfur careful feds spotted our bad license, do you have an escape plan? 
Edit: jk, yes, let's clarify this @erfur @eybisi

**Comment by ghost** [comment]
From [https://www.intel.com/content/www/us/en/legal/terms-of-use.html](https://www.intel.com/content/www/us/en/legal/terms-of-use.html):

> No License: Unless otherwise specified in the Materials themselves, you may not modify, copy, distribute, transmit, display, perform, reproduce, publish, license, create derivative works from, transfer, or sell any information, software, products or services obtained from the Web Sites. 

I'm not experienced in this stuff but if this covers the pdfs, sounds like derivative works are not allowed.

**Comment by figbux** [comment]
From second page of [Intel® 64 and IA-32 Architectures Software Developer’s Manual](https://software.intel.com/sites/default/files/managed/39/c5/325462-sdm-vol-1-2abcd-3abcd.pdf):

> No license (express or implied, by estoppel or otherwise) to any intellectual property rights is granted by this document

Well, so, sorry but no license we can acquire @jasperla . From now on, `copyleft` sign in the man-pages stands for the scripts that provided the pages to the user. If anyone has a contact in Intel co that can help us out on this, we can kindly ask for an exception-case license; because this project is clearly nothing but a good advertisement for Intel's itself.

I don't know if this would be a nifty bypass or not; but we can also keep only scripts and remove roff outputs in this repo; so no direct installation, each user must download the pdf from intel and reproduce his/her own manpages using scripts at here.

**Comment by jasperla** [comment]
@figbux for my particular case I'll package the scripts in a way that it's trivial for users to generate the manpages from the restrictively licensed PDF.

As for the scripts, could you add an explicit license marker to the project or scripts, something that is a copyleft license of course. Sorry for being a stickler, but an actual license like `GPLvX` or `MIT` is usable when it comes to redistribution whereas `copyleft` isn't.

Thanks for your time in clariflying this!

**Comment by figbux** [comment]
@jasperla MIT license added for the scripts, see `README.md` and `LICENSE` files. Also, `doit.sh` will now add MIT license to the outputs. For now, I'm not going to reproduce roff outputs; but when you package all of these, you can kindly update them via a PR if you wish.

Anyway, when you complete packaging, please add a brief installation info to `README.md` for OpenBSD. Or a link to your fork, if you wish.

Also you may wish to watch this repo as the bugs in the scripts are going to be fixed hopefully in near future by some good guy. You can close this issue anytime.

**Comment by jasperla** [comment]
Thanks!
